---
title: "Section 1"
format: html
---

## **Section 1 -** Responsible research evaluation and metrics overview


### **What are metrics?**

Research metrics are quantitative indicators about the performance of research outputs such as books, journal articles, datasets, and more. Metrics can be used to address many different parts of the research landscape from an individual paper or researcher to a journal or an institution. They can assess many different aspects of a research output, from how many citations it has, to where the output has been mentioned in policy or on social media.  


### **Principles of responsible metrics**

Historically, certain research metric practices have been used in misleading ways, and this has led to the development of several pieces of guidance related to the responsible use. This includes [DORA](https://sfdora.org/read/) and the [Leiden Manifesto](https://doi.org/10.1038/520429a), both of which were used to help shape the University of Derby’s own [responsible metrics policy](https://unimailderbyac.sharepoint.com/sites/URKEO/SitePages/Responsible-Use-of-Metrics.aspx). Another general set of principles for responsible research metric use is to abide by: Transparency, Appropriateness, Equality, Reproducible, and Continual Reassessment. 

When using research metrics for evaluation, it’s important to be as fair and transparent as possible. One of the most important principles, is that quantitative metrics should be used alongside qualitative evidence for evaluation purposes. 

### **Limitations of Metrics** 


-   Not all research outputs will be indexed
    -   Typically journal articles and some books may be indexed.
    -   STEM journals are more likely to be indexed than Arts, Humanities and Social Sciences.
    -   Smaller publishers may not index their journals.
    -   It can take up to six months from publication for articles to be indexed.
    -   Content may have been wrongly affiliated to a researcher or their content wrongly associated with someone else.  
-   Citations take a long time to accrue, favouring older papers over new.
-   Lack of context:
    -   there is no way of knowing if citations are positive or negative
-   Different cultures of research and publishing:
    -   volume of citations vary across disciplines, and what is considered a high number of citations for one research area might not be applicable to all disciplines
    -   publication type preferences can also depend on the discipline, with some research cultures preferring journal articles while others favour books or dataset publications
    -   cultures of research and publication will also influence publication timelines as well as how long a piece of research stays relevant in the discipline
    -   if you are subject expert you may have the contextual knowledge of what to expect but, if not it can be hard to determine whether it is good or not.
-   Requesting ‘top 10’ lists may automatically put early career researchers at a disadvantage.
-   Different software/databases count things in different ways so it may lead to results you cannot compare.
-   Researchers may use flawed metrics such as h-index, as a proxy of quality and not a true reflection of contribution.
-   Researchers may use metrics incorrectly or use the wrong type of metric for the assessment they are making; for example using a journal metric to infer the quality onto their article.


For further information, and guidance, as well as background information on the Research Excellence Framework which is alluded to in Section 4 of this module, it is highly recommended to refer to the [Responsible Research Metrics](https://uodlibrary.github.io/Responsible_Metrics_Module/) module. 